Addition of the Ghost balloon
SimonStnn/pop-a-loon pull request #340
Opened 2024-09-30 21:43 UTC by BanaantjeJowie

2024-10-01 18:31 UTC, SimonStnn commented on src/balloons/fast.ts
> +      riseDuration: [2000, 4000],
This is way to fast. Has this even been tested? It is not realistic for a user to be able to pop this. Keep the values at `[4000, 6500]`.

2024-10-01 18:33 UTC, SimonStnn commented on resources/balloons/ghost/balloon.svg
> +            100% { opacity: 0.1; }
Set minimum opacity to `0.2`.

2024-10-01 18:36 UTC, SimonStnn commented on src/balloons/ghost.ts
> +    };
Make the swing offset larger for the gost balloon. Could be more fitting.

2024-10-01 18:38 UTC, SimonStnn requested changes
Good work on the ghost balloon.

Don't forget to add it to the docs.

2024-10-01 18:53 UTC, SimonStnn commented on resources/balloons/ghost/balloon.svg
> +        svg {
Use a more specific selector.

2024-10-02 14:51 UTC, BanaantjeJowie commented on resources/balloons/ghost/balloon.svg
> +        }QA
Was probably on accident

2024-10-02 14:51 UTC, BanaantjeJowie commented on resources/balloons/ghost/balloon.svg
> +            100% { opacity: 0.1; }
Done boss!

2024-10-02 15:45 UTC, BanaantjeJowie commented on src/balloons/ghost.ts
> +    };
offset is now 25

2024-10-02 18:54 UTC, SimonStnn requested changes

2024-10-02 18:54 UTC, SimonStnn commented on resources/balloons/ghost/balloon.svg
> +            animation: fade 4s infinite; /* 4 seconds to fade in and out. To change the speed of the animation, change the value of 4s.*/
Ofcourse you can change the 4s here. The comment is utterly useless.

Use a css variable to set the animation length. This way the animation length can be changed via javascript. It would be nice if you add it as an option to the `Ghost.options` for the ghost balloon.

2024-10-02 18:54 UTC, SimonStnn commented on src/balloons/ghost.ts
> +
Format document.

2024-10-16 11:32 UTC, BanaantjeJowie commented on resources/balloons/ghost/balloon.svg
> +        svg {
no

2024-10-20 09:55 UTC, SimonStnn requested changes

2024-10-20 09:55 UTC, SimonStnn commented on src/balloons/ghost.ts
> +      swingOffset: 25,
Make the swingOffset bigger. 
```suggestion
      swingOffset: 25,
```

2024-10-20 09:55 UTC, SimonStnn commented on src/balloons/ghost.ts
> +      riseDuration: [15000, 20000],
The rise duration can be a bit longer
```suggestion
      riseDuration: [18000, 21000],
```

2024-10-21 09:48 UTC, SimonStnn approved these changes

2024-10-21 10:02 UTC, merged